#!/usr/bin/env python3
"""Generate port-only bot route data from committed solo setup waypoint tables.

Multiplayer setups have empty waypoint tables. Their corresponding solo setups
use the same stage coordinates, so copy only pad positions and graph links;
never replace the loaded multiplayer setup or its game objects.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
STAGES = (
    ("Facility", "LEVELID_FACILITY", "UsetuparkZ.c"),
    ("Temple", "LEVELID_TEMPLE", "UsetuparchZ.c"),
)
OUT = ROOT / "port/src/botnav_data.h"


def table(text, declaration):
    start = text.index(declaration) + len(declaration)
    return text[start:text.index("};", start)]


def parse(filename):
    text = (ROOT / "assets/obseg/setup" / filename).read_text()
    pads = re.findall(r"^\s*\{\s*\{([^{}]+)\},\s*\{[^{}]+\},\s*\{[^{}]+\},\s*\"[^\"]*\",\s*[^}]+\},?\s*$",
                      table(text, "PadRecord padlist[] = {"), re.M)
    coords = [[float(n.rstrip('f')) for n in pad.split(',')] for pad in pads]
    assert all(len(p) == 3 for p in coords)
    rows = re.findall(r"\{\s*(0x[0-9a-fA-F]+),\s*&path_table_(\d+),\s*[^}]+\}",
                      table(text, "waypoint pathwaypoints[] = {"))
    links = {int(i): [int(v) for v in vals.split(',') if int(v) >= 0]
             for i, vals in re.findall(r"^s32 path_table_(\d+)\[\] = \{([^}]+)\};", text, re.M)}
    assert rows and len(rows) == len(links) and len(rows) < 2048
    out = []
    edges = []
    for index, (pad, link) in enumerate(rows):
        assert int(link) == index and int(pad, 16) < len(coords)
        neighbours = links[index]
        assert all(0 <= n < len(rows) for n in neighbours)
        out.append((coords[int(pad, 16)], len(edges), len(neighbours)))
        edges.extend(neighbours)
    return out, edges


def emit():
    lines = ["/* Generated by tools_pc/gen_botnav.py from original solo setup graphs.",
             " * MP setups contain no route waypoints. This data is read only. */",
             "#ifndef PORT_BOTNAV_DATA_H", "#define PORT_BOTNAV_DATA_H",
             "#include <stdint.h>", "#include \"bondconstants.h\"",
             "typedef struct BotNavPoint { float x, y, z; uint16_t first, count; } BotNavPoint;", ""]
    parsed = []
    for name, level, filename in STAGES:
        points, edges = parse(filename)
        parsed.append((name, level, len(points)))
        lines.append(f"static const uint16_t botNav{name}Edges[] = {{")
        for i in range(0, len(edges), 20):
            lines.append("    " + ", ".join(map(str, edges[i:i+20])) + ",")
        lines.append("};")
        lines.append(f"static const BotNavPoint botNav{name}[] = {{")
        for (x, y, z), first, count in points:
            lines.append(f"    {{ {x:.1f}f, {y:.1f}f, {z:.1f}f, {first}, {count} }},")
        lines.extend(["};", ""])
    lines.extend(["static inline const BotNavPoint *botNavForStage(int stage,",
                  "    const uint16_t **edges, int *count)", "{", "    switch (stage) {"])
    for name, level, n in parsed:
        lines.extend([f"    case {level}:", f"        *edges = botNav{name}Edges; *count = {n}; return botNav{name};"])
    lines.extend(["    default: *edges = 0; *count = 0; return 0;", "    }", "}", "#endif", ""])
    OUT.write_text("\n".join(lines))
    for name, _, count in parsed:
        print(f"{name}: {count} waypoints")


if __name__ == "__main__":
    emit()
